server:
  servlet:
    contextPath: /demo-service
  port: 8002
  data:
    rest:
      basePath: '/api'
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: SA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

spring:
 h2:
  console:
   enabled: true
   path: /h2